- name: Play for Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print a Value
      ansible.builtin.debug:
        msg: URL - {{URL}}

# Since it is a play level variable the scope is completely on all tasks.

