#- name: Download and UnZip the {{COMPONENT}} Content
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes

- name: Download and UnZip the {{COMPONENT}} Content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes
  when: GIT_DOWNLOAD is defined

- name: Download {{COMPONENT}} from Nexus
  ansible.builtin.get_url:
    url: http://nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp
    username: "{{NEXUS_USERNAME}}"
    password: "{{NEXUS_PASSWORD}}"
  when: GIT_DOWNLOAD is not defined